version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ENV=production
    volumes:
      - .:/app
    command: python ./your-daemon-or-script.py
